# -*- coding: utf-8 -*-
"""experiment2_normalize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwLrTteeYqCc8B9sgoQveOmrFhqN6Vrl

# Experiment 2 - 정규화 방법 비교
실험 목적: 전체 feature(stress_level 제외) 고정 후 StandardScaler vs MinMaxScaler 성능 비교

## 1. 라이브러리 임포트
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

"""## 2. 데이터 로드 및 결측치 처리"""

data = pd.read_csv('/content/sample_data/developer_burnout_dataset_7000.csv')
print('데이터 크기:', data.shape)
data.head()

data.fillna(data.mean(numeric_only=True), inplace=True)

data['burnout_level'].fillna(data['burnout_level'].mode()[0], inplace=True)

print('결측치 처리 후:')
print(data.isnull().sum())

"""## 3. 타겟 라벨 인코딩"""

data['burnout_level'] = data['burnout_level'].map({'Low': 0, 'Medium': 1, 'High': 2})
print(data['burnout_level'].value_counts())

"""## 4. Feature / Target 정의

- experiment1 결과: 전체 feature(stress_level 제외)가 더 좋은 모델 → 고정
- 이번 실험 변수: 정규화 방법 (StandardScaler vs MinMaxScaler)
"""

feature_columns = ['age','experience_years','daily_work_hours','sleep_hours',
                   'caffeine_intake','bugs_per_day','commits_per_day',
                   'meetings_per_day','screen_time','exercise_hours']
target_column = ['burnout_level']

feature = data[feature_columns]
target  = data[target_column]

X_train, X_test, y_train, y_test = train_test_split(
    feature, target, test_size=0.2, random_state=42)

"""## 5. 정규화 적용 (SC / MM 각각)"""

sc = StandardScaler()
mm = MinMaxScaler()

X_train_sc = sc.fit_transform(X_train)
X_test_sc  = sc.transform(X_test)

X_train_mm = mm.fit_transform(X_train)
X_test_mm  = mm.transform(X_test)

print(X_train_sc.shape, X_train_mm.shape)

"""## 6. Tensor 변환"""

X_train_sc = torch.FloatTensor(X_train_sc)
X_test_sc  = torch.FloatTensor(X_test_sc)
X_train_mm = torch.FloatTensor(X_train_mm)
X_test_mm  = torch.FloatTensor(X_test_mm)

y_train_sc = torch.LongTensor(y_train.values)
y_test_sc  = torch.LongTensor(y_test.values)
y_train_mm = torch.LongTensor(y_train.values)
y_test_mm  = torch.LongTensor(y_test.values)

"""## 7. DataLoader"""

train_loader_sc = DataLoader(TensorDataset(X_train_sc, y_train_sc), batch_size=64, shuffle=True)
test_loader_sc  = DataLoader(TensorDataset(X_test_sc,  y_test_sc),  batch_size=64, shuffle=False)
train_loader_mm = DataLoader(TensorDataset(X_train_mm, y_train_mm), batch_size=64, shuffle=True)
test_loader_mm  = DataLoader(TensorDataset(X_test_mm,  y_test_mm),  batch_size=64, shuffle=False)

"""## 8. 모델 정의"""

class BurnoutModel(nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.layer1 = nn.Linear(input_dim, 64)
    self.layer2 = nn.Linear(64, 32)
    self.layer3 = nn.Linear(32, 16)
    self.layer4 = nn.Linear(16, 3)
    self.relu    = nn.ReLU()
    self.softmax = nn.Softmax()

  def forward(self, x):
    x = self.relu(self.layer1(x))
    x = self.relu(self.layer2(x))
    x = self.relu(self.layer3(x))
    x = self.layer4(x)
    return x

model_sc = BurnoutModel(10)
model_mm = BurnoutModel(10)

criterion_sc = nn.CrossEntropyLoss()
criterion_mm = nn.CrossEntropyLoss()
optimizer_sc = optim.Adam(model_sc.parameters(), lr=0.001)
optimizer_mm = optim.Adam(model_mm.parameters(), lr=0.001)

"""## 9. StandardScaler 모델 학습"""

epochs = 50
history_sc = {"train_loss": [], "test_loss": [], "train_acc": [], "test_acc": []}

for epoch in range(epochs):
  model_sc.train()
  train_loss, correct, total = 0, 0, 0

  for X, y in train_loader_sc:
    optimizer_sc.zero_grad()
    outputs = model_sc(X)
    y_processed = y.long().squeeze()
    loss = criterion_sc(outputs, y_processed)
    loss.backward()
    optimizer_sc.step()
    train_loss += loss.item()
    predicted = torch.argmax(outputs, dim=1)
    correct += (predicted == y_processed).sum().item()
    total += y.size(0)

  train_accuracy = correct / total
  avg_train_loss = train_loss / len(train_loader_sc)

  model_sc.eval()
  test_loss, test_correct, test_total = 0, 0, 0

  with torch.no_grad():
    for X, y in test_loader_sc:
      outputs = model_sc(X)
      y_processed = y.long().squeeze()
      loss = criterion_sc(outputs, y_processed)
      test_loss += loss.item()
      predicted = torch.argmax(outputs, dim=1)
      test_correct += (predicted == y_processed).sum().item()
      test_total += y.size(0)

    test_accuracy = test_correct / test_total
    avg_test_loss = test_loss / len(test_loader_sc)
    history_sc["train_loss"].append(avg_train_loss)
    history_sc["test_loss"].append(avg_test_loss)
    history_sc["train_acc"].append(train_accuracy)
    history_sc["test_acc"].append(test_accuracy)
    print(f"Epoch {epoch+1}/{epochs}, Train Loss: {avg_train_loss:.4f}, Test Loss: {avg_test_loss:.4f}, Train Acc: {train_accuracy:.4f}, Test Acc: {test_accuracy:.4f}")

"""## 10. MinMaxScaler 모델 학습"""

epochs = 50
history_mm = {"train_loss": [], "test_loss": [], "train_acc": [], "test_acc": []}

for epoch in range(epochs):
  model_mm.train()
  train_loss, correct, total = 0, 0, 0

  for X, y in train_loader_mm:
    optimizer_mm.zero_grad()
    outputs = model_mm(X)
    y_processed = y.long().squeeze()
    loss = criterion_mm(outputs, y_processed)
    loss.backward()
    optimizer_mm.step()
    train_loss += loss.item()
    predicted = torch.argmax(outputs, dim=1)
    correct += (predicted == y_processed).sum().item()
    total += y.size(0)

  train_accuracy = correct / total
  avg_train_loss = train_loss / len(train_loader_mm)

  model_mm.eval()
  test_loss, test_correct, test_total = 0, 0, 0

  with torch.no_grad():
    for X, y in test_loader_mm:
      outputs = model_mm(X)
      y_processed = y.long().squeeze()
      loss = criterion_mm(outputs, y_processed)
      test_loss += loss.item()
      predicted = torch.argmax(outputs, dim=1)
      test_correct += (predicted == y_processed).sum().item()
      test_total += y.size(0)

    test_accuracy = test_correct / test_total
    avg_test_loss = test_loss / len(test_loader_mm)
    history_mm["train_loss"].append(avg_train_loss)
    history_mm["test_loss"].append(avg_test_loss)
    history_mm["train_acc"].append(train_accuracy)
    history_mm["test_acc"].append(test_accuracy)
    print(f"Epoch {epoch+1}/{epochs}, Train Loss: {avg_train_loss:.4f}, Test Loss: {avg_test_loss:.4f}, Train Acc: {train_accuracy:.4f}, Test Acc: {test_accuracy:.4f}")

"""## 11. 결과 시각화"""

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Loss 비교
axes[0].plot(history_sc['train_loss'], label='SC Train Loss', color='blue', linestyle='--')
axes[0].plot(history_sc['test_loss'],  label='SC Test Loss',  color='blue')
axes[0].plot(history_mm['train_loss'], label='MM Train Loss', color='red',  linestyle='--')
axes[0].plot(history_mm['test_loss'],  label='MM Test Loss',  color='red')
axes[0].set_title('Loss 비교 (StandardScaler vs MinMaxScaler)')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()

# Accuracy 비교
axes[1].plot(history_sc['train_acc'], label='SC Train Acc', color='blue', linestyle='--')
axes[1].plot(history_sc['test_acc'],  label='SC Test Acc',  color='blue')
axes[1].plot(history_mm['train_acc'], label='MM Train Acc', color='red',  linestyle='--')
axes[1].plot(history_mm['test_acc'],  label='MM Test Acc',  color='red')
axes[1].set_title('Accuracy 비교 (StandardScaler vs MinMaxScaler)')
axes[1].set_xlabel('Epochs')
axes[1].set_ylabel('Accuracy')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"[StandardScaler] Train Acc: {history_sc['train_acc'][-1]:.4f} | Test Acc: {history_sc['test_acc'][-1]:.4f}")
print(f"[MinMaxScaler]   Train Acc: {history_mm['train_acc'][-1]:.4f} | Test Acc: {history_mm['test_acc'][-1]:.4f}")

"""## 실험 결과

- Test Accuracy와 Loss는 두 방법 모두 비슷
- StandardScaler는 Train/Test 간 과적합이 발생
- MinMaxScaler는 Train/Test가 안정적으로 수렴
- → **MinMaxScaler 채택**

다음 실험(experiment3)에서는 MinMaxScaler 고정 후 결측치 처리 방법 비교 예정
"""