# -*- coding: utf-8 -*-
"""experiment1_feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xoOul8Xh_T9JqULKgQKlR4DhOkl2o-W

# Experiment 1 - Feature Selection
번아웃과 상관계수가 낮은 feature를 포함했을 때 vs 제외했을 때 비교
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

"""## 1. 데이터 로드 및 결측치 처리"""

data = pd.read_csv('/content/sample_data/developer_burnout_dataset_7000.csv')
print('데이터 크기:', data.shape)
data.head()

data.fillna(data.mean(numeric_only=True), inplace=True)
data['burnout_level'].fillna(data['burnout_level'].mode()[0], inplace=True)
print('결측치 처리 후:')
print(data.isnull().sum())

"""## 2. 타겟 라벨 인코딩"""

data['burnout_level'] = data['burnout_level'].map({'Low': 0, 'Medium': 1, 'High': 2})
print(data['burnout_level'].value_counts())

"""## 3. 상관관계 시각화 (EDA)"""

plt.figure(figsize=(10, 10))
sns.heatmap(data.corr(numeric_only=True), annot=True, fmt='0.2f')
plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

print('burnout_level 기준 상관계수:')
print(data.corr(numeric_only=True)['burnout_level'].sort_values(ascending=False))

"""**EDA 결과**

- stress_level: 상관계수 0.91 → 너무 높아서 제외 (정보 누수 우려)
- daily_work_hours, screen_time, bugs_per_day: 중간 이상 상관관계 → 유의미
- age, experience_years, commits_per_day, exercise_hours: 상관계수 0.02 이하 → 거의 무관

**실험 설계**

- feature_all: stress_level 제외한 전체 10개 feature
- feature_high: 상관계수 높은 6개 feature만 사용

## 4. Feature / Target 정의 및 데이터 분할
"""

feature_all  = ['age', 'experience_years', 'daily_work_hours', 'sleep_hours',
                'caffeine_intake', 'bugs_per_day', 'commits_per_day',
                'meetings_per_day', 'screen_time', 'exercise_hours']

feature_high = ['daily_work_hours', 'sleep_hours', 'caffeine_intake',
                'bugs_per_day', 'meetings_per_day', 'screen_time']

target = ['burnout_level']

X_train_all,  X_test_all,  y_train_all,  y_test_all  = train_test_split(
    data[feature_all],  data[target], test_size=0.2, random_state=40)

X_train_high, X_test_high, y_train_high, y_test_high = train_test_split(
    data[feature_high], data[target], test_size=0.2, random_state=41)

"""## 5. 정규화 및 Tensor 변환"""

sc  = StandardScaler()
sc1 = StandardScaler()

X_train_all  = sc.fit_transform(X_train_all)
X_test_all   = sc.transform(X_test_all)
X_train_high = sc1.fit_transform(X_train_high)
X_test_high  = sc1.transform(X_test_high)

X_train_all  = torch.FloatTensor(X_train_all)
X_test_all   = torch.FloatTensor(X_test_all)
y_train_all  = torch.FloatTensor(y_train_all.values)
y_test_all   = torch.FloatTensor(y_test_all.values)
X_train_high = torch.FloatTensor(X_train_high)
X_test_high  = torch.FloatTensor(X_test_high)
y_train_high = torch.FloatTensor(y_train_high.values)
y_test_high  = torch.FloatTensor(y_test_high.values)

print(X_train_all.shape, y_train_all.shape)
print(X_train_high.shape, y_train_high.shape)

"""## 6. DataLoader"""

train_all_loader  = DataLoader(TensorDataset(X_train_all,  y_train_all),  batch_size=64, shuffle=True)
test_all_loader   = DataLoader(TensorDataset(X_test_all,   y_test_all),   batch_size=64, shuffle=False)
train_high_loader = DataLoader(TensorDataset(X_train_high, y_train_high), batch_size=64, shuffle=True)
test_high_loader  = DataLoader(TensorDataset(X_test_high,  y_test_high),  batch_size=64, shuffle=False)

"""## 7. 모델 정의"""

class BurnoutModel(nn.Module):
  def __init__(self, input_dim):
    super().__init__()
    self.layer1 = nn.Linear(input_dim, 64)
    self.layer2 = nn.Linear(64, 32)
    self.layer3 = nn.Linear(32, 16)
    self.layer4 = nn.Linear(16, 3)
    self.relu = nn.ReLU()
    self.softmax = nn.Softmax()

  def forward(self, x):
    x = self.relu(self.layer1(x))
    x = self.relu(self.layer2(x))
    x = self.relu(self.layer3(x))
    x = self.softmax(self.layer4(x))
    return x

model_all  = BurnoutModel(10)
model_high = BurnoutModel(6)

criterion_all  = nn.CrossEntropyLoss()
criterion_high = nn.CrossEntropyLoss()
optimizer_all  = optim.Adam(model_all.parameters(),  lr=0.001)
optimizer_high = optim.Adam(model_high.parameters(), lr=0.001)

"""## 8. 전체 Feature 모델 학습"""

epochs = 50
history_all = {"train_loss": [], "test_loss": [], "train_acc": [], "test_acc": []}

for epoch in range(epochs):
  model_all.train()
  train_loss = 0
  correct = 0
  total = 0

  for X, y in train_all_loader:
    optimizer_all.zero_grad()
    outputs = model_all(X)
    y_processed = y.long().squeeze()
    loss = criterion_all(outputs, y_processed)
    loss.backward()
    optimizer_all.step()
    train_loss += loss.item()
    predicted = torch.argmax(outputs, dim=1)
    correct += (predicted == y_processed).sum().item()
    total += y.size(0)

  train_accuracy = correct / total
  avg_train_all_loss = train_loss / len(train_all_loader)

  model_all.eval()
  test_loss = 0
  test_correct = 0
  test_total = 0

  with torch.no_grad():
    for X, y in test_all_loader:
      outputs = model_all(X)
      y_processed = y.long().squeeze()
      loss = criterion_all(outputs, y_processed)
      test_loss += loss.item()
      predicted = torch.argmax(outputs, dim=1)
      test_correct += (predicted == y_processed).sum().item()
      test_total += y.size(0)

    test_accuracy = test_correct / test_total
    avg_test_all_loss = test_loss / len(test_all_loader)
    history_all["train_loss"].append(avg_train_all_loss)
    history_all["test_loss"].append(avg_test_all_loss)
    history_all["train_acc"].append(train_accuracy)
    history_all["test_acc"].append(test_accuracy)
    print(f"Epoch {epoch+1}/{epochs}, Train Loss: {avg_train_all_loss:.4f}, Test Loss: {avg_test_all_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Test Accuracy: {test_accuracy:.4f}")

"""## 9. 상관관계 높은 Feature 모델 학습"""

epochs = 50
history_high = {"train_loss": [], "test_loss": [], "train_acc": [], "test_acc": []}

for epoch in range(epochs):
  model_high.train()
  train_loss = 0
  correct = 0
  total = 0

  for X, y in train_high_loader:
    optimizer_high.zero_grad()
    outputs = model_high(X)
    y_processed = y.long().squeeze()
    loss = criterion_high(outputs, y_processed)
    loss.backward()
    optimizer_high.step()
    train_loss += loss.item()
    predicted = torch.argmax(outputs, dim=1)
    correct += (predicted == y_processed).sum().item()
    total += y.size(0)

  train_accuracy = correct / total
  avg_train_loss = train_loss / len(train_high_loader)

  model_high.eval()
  test_loss = 0
  test_correct = 0
  test_total = 0

  with torch.no_grad():
    for X, y in test_high_loader:
      outputs = model_high(X)
      y_processed = y.long().squeeze()
      loss = criterion_high(outputs, y_processed)
      test_loss += loss.item()
      predicted = torch.argmax(outputs, dim=1)
      test_correct += (predicted == y_processed).sum().item()
      test_total += y.size(0)

    test_accuracy = test_correct / test_total
    avg_test_loss = test_loss / len(test_high_loader)
    history_high["train_loss"].append(avg_train_loss)
    history_high["test_loss"].append(avg_test_loss)
    history_high["train_acc"].append(train_accuracy)
    history_high["test_acc"].append(test_accuracy)
    print(f"Epoch {epoch+1}/{epochs}, Train Loss: {avg_train_loss:.4f}, Test Loss: {avg_test_loss:.4f}, Train Accuracy: {train_accuracy:.4f}, Test Accuracy: {test_accuracy:.4f}")

"""## 10. 결과 시각화"""

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

axes[0].plot(history_all['train_loss'],  label='All Train Loss',  color='blue')
axes[0].plot(history_all['test_loss'],   label='All Test Loss',   color='red')
axes[0].plot(history_high['train_loss'], label='High Train Loss', color='green')
axes[0].plot(history_high['test_loss'],  label='High Test Loss',  color='orange')
axes[0].set_title('Loss 비교 (전체 Feature vs 상관관계 높은 Feature)')
axes[0].set_xlabel('Epochs')
axes[0].set_ylabel('Loss')
axes[0].legend()

axes[1].plot(history_all['train_acc'],  label='All Train Accuracy',  color='blue')
axes[1].plot(history_all['test_acc'],   label='All Test Accuracy',   color='red')
axes[1].plot(history_high['train_acc'], label='High Train Accuracy', color='green')
axes[1].plot(history_high['test_acc'],  label='High Test Accuracy',  color='orange')
axes[1].set_title('Accuracy 비교 (전체 Feature vs 상관관계 높은 Feature)')
axes[1].set_xlabel('Epochs')
axes[1].set_ylabel('Accuracy')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"[전체 Feature]     Train Acc: {history_all['train_acc'][-1]:.4f} | Test Acc: {history_all['test_acc'][-1]:.4f}")
print(f"[높은 상관 Feature] Train Acc: {history_high['train_acc'][-1]:.4f} | Test Acc: {history_high['test_acc'][-1]:.4f}")

"""## 실험 결과

- Test Accuracy 기준: 전체 feature > 상관관계 높은 feature만 사용
- 결론: 상관계수가 낮은 feature라도 모델 학습에 미세한 패턴 기여 가능
- → 전체 feature(stress_level 제외)를 사용하는 것이 더 좋은 모델
- 다음 실험(experiment2)에서는 전체 feature 고정 후 정규화 방법 비교 예정
"""